// Реплики головы — субтитры под ней. id совпадает с именем mp3 в assets/voice/ (см. voice-script.md).
// {name}, {nameGen} подставляются из content/site.json. Перенос строки — \n.
export const LINES = {
  ru: {
    hello_1: 'Привет! Я голова {nameGen}. Тело на созвоне, так что работы показываю я.',
    hello_2: 'Наведи на папку — покажу, что внутри.',
    hello_2_touch: 'Нажми на папку — покажу, что внутри.',
    hello_back: 'О, снова ты! Я запомнил твоё лицо. Надеюсь, ты моё тоже.\nПродолжим? Выбирай.',
    folder_digital: 'Цифровые продукты: приложения, сервисы, дашборды.',
    folder_marketing: 'Маркетинг и коммуникация: кампании, плакаты, промо.',
    folder_identity: 'Айдентика и брендинг: знаки, упаковка, фирменные системы.',
    drag_folder_1: 'Эй, я их по порядку раскладывал.',
    drag_folder_2: 'Клади куда хочешь. Это теперь и твой рабочий стол.',
    drag_face: 'Э! Мне так не видно.',
    cv: 'Резюме уже скачивается. Там всё то же, только без головы.',
    sound_on: 'О, звук. Теперь меня ещё и слышно.',
    catalog_hi: 'Я тут, в уголке. Крути — проекты поедут по кругу.',
    catalog_hi_touch: 'Я тут, в уголке. Листай — тут все проекты.',
    open_project: 'Хороший выбор. Этот проект я помню в лицо.',
    filter_all: 'Всё сразу. Смело.',
    filter_digital: 'Интерфейсы. Мой любимый способ спорить с разработчиками.',
    filter_marketing: 'Кампании и плакаты. Тут я особенно громкий.',
    filter_identity: 'Айдентика. Где каждый пиксель — чьё-то «а давайте ещё вариант».',
    empty: 'Тут пока пусто. Даже я удивлён.',
    idle_1: 'Я всё ещё тут. И всё ещё без тела.',
    idle_2: 'Можно меня потянуть. Я разрешаю.',
    idle_3: 'Очки, кстати, снимаются. Но лучше не надо.',
    idle_4: 'Папки можно таскать. Обратно я их не разложу — рук нет.',
    grab_nose_1: 'Это нос. Он мне ещё пригодится.',
    grab_nose_2: 'Аккуратнее, я им дизайн нюхаю.',
    grab_mouth_1: 'Ммм-мф! Я вообще-то разговариваю!',
    grab_mouth_2: 'Рот не трогать, им я защищаю макеты.',
    grab_cheek_1: 'Щёки — мой тактильный интерфейс.',
    grab_cheek_2: 'Ай. Но, признаю, приятно.',
    grab_ear_1: 'Я тебя и так слышу!',
    grab_ear_2: 'Ухо — не ползунок громкости.',
    grab_hair_1: 'Причёску делали дольше, чем некоторые логотипы.',
    grab_hair_2: 'Не лохмать, у меня созвон.',
    grab_chin_1: 'Подбородок уверенный, как дедлайн.',
    grab_forehead_1: 'Там идеи. Не выдави.',
    grab_eye_1: 'Эй, это глаз!',
    grab_glasses_1: 'Осторожно, это оптика!',
    stretch_big_1: 'Ого, я так ещё не растягивался. Даже на дейли.',
    stretch_big_2: 'Вот это гибкость. Можно в резюме.',
    poke_1: 'Ай!',
    poke_2: 'Тык принят.',
    poke_3: 'Ещё раз — и выставлю счёт.',
    glasses_off_1: 'Эй, верни очки! Теперь всё как в тумане.',
    glasses_off_2: 'Без очков я вижу только размытое портфолио.',
    glasses_look: 'Смотри сквозь линзы — там резко.',
    glasses_self: 'Ладно, сам надену.',
    glasses_on: 'Спасибо. Мир снова резкий.',
    tilt_hi: 'О, крутишь телефон? Я всё вижу.',
    tilt_on: 'Есть контакт. Наклоняй телефон — я слежу.',
    tilt_denied: 'Ладно, буду следить за пальцем.',
  },
  // Английские реплики включаются вместе с английской версией сайта (content/site.json → languages)
  en: {
    hello_1: 'Hi! I’m {name}’s head. The body is on a call, so I’m the one showing the work.',
    hello_2: 'Hover over a folder — I’ll show you what’s inside.',
    hello_2_touch: 'Tap a folder — I’ll show you what’s inside.',
    hello_back: 'Oh, you again! I remember your face. Hope you remember mine.\nShall we continue? Pick one.',
    folder_digital: 'Digital products: apps, services, dashboards.',
    folder_marketing: 'Marketing and communication: campaigns, posters, promo.',
    folder_identity: 'Identity and branding: marks, packaging, brand systems.',
    drag_folder_1: 'Hey, I had those in order.',
    drag_folder_2: 'Put it wherever. It’s your desktop now too.',
    drag_face: 'Hey! I can’t see like this.',
    cv: 'The CV is downloading. Same story, minus the head.',
    sound_on: 'Oh, sound. Now you can hear me too.',
    catalog_hi: 'I’m over here, in the corner. Scroll — the projects go round.',
    catalog_hi_touch: 'I’m over here, in the corner. Scroll — all the projects are here.',
    open_project: 'Good pick. I know this one by heart. Well — by head.',
    filter_all: 'Everything at once. Bold.',
    filter_digital: 'Interfaces. My favourite way to argue with developers.',
    filter_marketing: 'Campaigns and posters. This is where I get loud.',
    filter_identity: 'Identity. Where every pixel is someone’s “let’s try one more option”.',
    empty: 'Nothing here yet. Even I’m surprised.',
    idle_1: 'Still here. Still no body.',
    idle_2: 'You can pull me. I allow it.',
    idle_3: 'The glasses come off, by the way. Better not, though.',
    idle_4: 'The folders can be dragged. I won’t put them back — no hands.',
    grab_nose_1: 'That’s my nose. I still need it.',
    grab_nose_2: 'Careful, I sniff out design with that.',
    grab_mouth_1: 'Mmm-mph! I’m talking here!',
    grab_mouth_2: 'Hands off the mouth — I defend mockups with it.',
    grab_cheek_1: 'Cheeks: my tactile interface.',
    grab_cheek_2: 'Ouch. But, I admit, kind of nice.',
    grab_ear_1: 'I can hear you just fine!',
    grab_ear_2: 'The ear is not a volume slider.',
    grab_hair_1: 'This haircut took longer than some logos.',
    grab_hair_2: 'Don’t mess it up, I have a call.',
    grab_chin_1: 'A chin as firm as a deadline.',
    grab_forehead_1: 'Ideas in there. Don’t squeeze them out.',
    grab_eye_1: 'Hey, that’s an eye!',
    grab_glasses_1: 'Careful, that’s optics!',
    stretch_big_1: 'Whoa, I’ve never stretched like that. Not even at stand-up.',
    stretch_big_2: 'Now that’s flexibility. One for the CV.',
    poke_1: 'Ouch!',
    poke_2: 'Poke received.',
    poke_3: 'One more and I’m sending an invoice.',
    glasses_off_1: 'Hey, give the glasses back! Everything’s a blur.',
    glasses_off_2: 'Without glasses all I see is a blurry portfolio.',
    glasses_look: 'Look through the lenses — it’s sharp in there.',
    glasses_self: 'Fine, I’ll put them on myself.',
    glasses_on: 'Thanks. The world is sharp again.',
    tilt_hi: 'Oh, tilting the phone? I see everything.',
    tilt_on: 'Contact. Tilt the phone — I’m watching.',
    tilt_denied: 'Fine, I’ll follow your finger.',
  },
};

// Какие реплики на какое действие
export const REACTIONS = {
  nose: ['grab_nose_1', 'grab_nose_2'], mouth: ['grab_mouth_1', 'grab_mouth_2'], cheek: ['grab_cheek_1', 'grab_cheek_2'],
  ear: ['grab_ear_1', 'grab_ear_2'], hair: ['grab_hair_1', 'grab_hair_2'], chin: ['grab_chin_1'], forehead: ['grab_forehead_1'],
  eye: ['grab_eye_1'], glasses: ['grab_glasses_1'],
  stretch: ['stretch_big_1', 'stretch_big_2'], poke: ['poke_1', 'poke_2', 'poke_3'],
  glassesOff: ['glasses_off_1', 'glasses_off_2'],
  dragFolder: ['drag_folder_1', 'drag_folder_2'],
  idle: ['idle_1', 'idle_2', 'idle_4', 'idle_3'],
};
