// Реплики головы — субтитры под ней. id совпадает с именем mp3 в assets/voice/ (см. voice-script.md).
// {name}, {nameGen}, {role} подставляются из content/site.json. Перенос строки — \n.
// Здесь — исходные тексты. Свои правит владелец сайта в админке («Реплики головы»): они хранятся в content/site.json
// (поле lines) и ложатся поверх исходных; пустая строка там значит «в этой ситуации промолчать» (см. linesFor ниже).
export const LINES = {
  ru: {
    hello_1: 'Привет! Я голова {nameGen}. Тело на созвоне, так что работы показываю я.',
    hello_2: 'Наведи на папку — покажу, что внутри.',
    hello_2_touch: 'Нажми на папку — покажу, что внутри.',
    hello_2_strip: 'Листай папки — покажу, что внутри.',
    hello_2_clean: 'Жми «Все работы» — там кейсы. А меня можно потянуть: я резиновый.',
    hello_back: 'О, снова ты! Я запомнил твоё лицо. Надеюсь, ты моё тоже.\nПродолжим? Выбирай.',
    hello_back_clean: 'О, снова ты! Я запомнил твоё лицо. Надеюсь, ты моё тоже.\nПродолжим?',
    folder_digital: 'Цифровые продукты: приложения, сервисы, дашборды.',
    folder_marketing: 'Маркетинг и коммуникация: кампании, плакаты, промо.',
    folder_identity: 'Айдентика и брендинг: знаки, упаковка, фирменные системы.',
    drag_folder_1: 'Эй, я их по порядку раскладывал.',
    drag_folder_2: 'Клади куда хочешь. Это теперь и твой рабочий стол.',
    drag_folder_far: 'Эй, не убирай её далеко — другие не увидят мои кэээйсы!',
    drag_face: 'Э! Мне так не видно.',
    cv: 'Резюме уже скачивается. Там всё то же, только без головы.',
    sound_on: 'О, звук. Теперь меня ещё и слышно.',
    catalog_hi: 'Я тут, в уголке. Крути — проекты поедут лентой.',
    like_1: 'О, отметил. Мне он тоже нравится.',
    like_2: 'Лайк засчитан. Павел будет рад.',
    catalog_hi_touch: 'Я тут, в уголке. Листай — тут все проекты.',
    open_project: 'Хороший выбор. Этот проект я помню в лицо.',
    filter_all: 'Всё сразу. Смело.',
    filter_digital: 'Интерфейсы. Мой любимый способ спорить с разработчиками.',
    filter_marketing: 'Кампании и плакаты. Тут я особенно громкий.',
    filter_identity: 'Айдентика. Где каждый пиксель — чьё-то «а давайте ещё вариант».',
    empty: 'Тут пока пусто. Даже я удивлён.',
    idle_hey_1: 'Эй, ты тут?',
    idle_hey_2: 'Куда делся?',
    idle_hey_3: 'Ау! Я вообще-то работы показываю.',
    idle_1: 'Я всё ещё тут. И всё ещё без тела.',
    idle_2: 'Можно меня потянуть. Я разрешаю.',
    idle_3: 'Очки, кстати, снимаются. Но лучше не надо.',
    idle_4: 'Папки можно таскать. Обратно я их не разложу — рук нет.',
    idle_5: 'Кейсы сами себя не посмотрят. Жми «Все работы».',
    grab_nose_1: 'Это нос. Он мне ещё пригодится.',
    grab_nose_2: 'Аккуратнее, я им дизайн нюхаю.',
    grab_mouth_1: 'Ммм-мф! Я вообще-то разговариваю!',
    grab_mouth_2: 'Рот не трогать, им я защищаю макеты.',
    grab_cheek_1: 'Щёки — мой тактильный интерфейс.',
    grab_cheek_2: 'Ай. Но, признаю, приятно.',
    grab_ear_1: 'Я тебя и так слышу!',
    grab_ear_2: 'Ухо — не ползунок громкости.',
    grab_hair_1: 'Причёску делали дольше, чем некоторые логотипы.',
    grab_hair_2: 'Не лохмать, у меня созвон.',
    grab_chin_1: 'Подбородок уверенный, как дедлайн.',
    grab_forehead_1: 'Там идеи. Не выдави.',
    grab_eye_1: 'Эй, это глаз!',
    grab_glasses_1: 'Осторожно, это оптика!',
    stretch_big_1: 'Ого, я так ещё не растягивался. Даже на дейли.',
    stretch_big_2: 'Вот это гибкость. Можно в резюме.',
    poke_1: 'Ай!',
    poke_2: 'Тык принят.',
    poke_3: 'Ещё раз — и выставлю счёт.',
    glasses_off_1: 'Эй, верни очки! Теперь всё как в тумане.',
    glasses_off_2: 'Без очков я вижу только размытое портфолио.',
    glasses_look: 'Смотри сквозь линзы — там резко.',
    glasses_self: 'Ладно, сам надену.',
    glasses_on: 'Спасибо. Мир снова резкий.',
    tilt_hi: 'О, крутишь телефон? Я всё вижу.',
    tilt_on: 'Есть контакт. Наклоняй телефон — я слежу.',
    tilt_denied: 'Ладно, обойдусь без наклона.',
    spit_warn: 'Ты там уснул? Сейчас плюну.',
    spit_1: 'Тьфу!',
    spit_2: 'Я предупреждал.',
    spit_3: 'Это тебе за бездействие.',
    spit_4: 'Тела нет, а слюны — сколько угодно.',
    spit_5: 'И сюда.',
    spit_6: 'Не шевелись, я рисую.',
    spit_7: 'Ещё чуть-чуть.',
    spit_done: 'Всё, экран мой. Пошевелись — вытру.',
    spit_back: 'О, живой! Ладно, вытираю.',
  },
  // Английские реплики включаются вместе с английской версией сайта (content/site.json → languages)
  en: {
    hello_1: 'Hi! I’m {name}’s head. The body is on a call, so I’m the one showing the work.',
    hello_2: 'Hover over a folder — I’ll show you what’s inside.',
    hello_2_touch: 'Tap a folder — I’ll show you what’s inside.',
    hello_2_strip: 'Swipe the folders — I’ll show you what’s inside.',
    hello_2_clean: 'Hit “All work” — the case studies are in there. And go on, pull me: I’m rubbery.',
    hello_back: 'Oh, you again! I remember your face. Hope you remember mine.\nShall we continue? Pick one.',
    hello_back_clean: 'Oh, you again! I remember your face. Hope you remember mine.\nShall we continue?',
    folder_digital: 'Digital products: apps, services, dashboards.',
    folder_marketing: 'Marketing and communication: campaigns, posters, promo.',
    folder_identity: 'Identity and branding: marks, packaging, brand systems.',
    drag_folder_1: 'Hey, I had those in order.',
    drag_folder_2: 'Put it wherever. It’s your desktop now too.',
    drag_folder_far: 'Hey, not too far — nobody will see my caaases!',
    drag_face: 'Hey! I can’t see like this.',
    cv: 'The CV is downloading. Same story, minus the head.',
    sound_on: 'Oh, sound. Now you can hear me too.',
    catalog_hi: 'I’m over here, in the corner. Scroll — the projects slide by.',
    like_1: 'Oh, noted. I like that one too.',
    like_2: 'Like counted. Pavel will be pleased.',
    catalog_hi_touch: 'I’m over here, in the corner. Scroll — all the projects are here.',
    open_project: 'Good pick. I know this one by heart. Well — by head.',
    filter_all: 'Everything at once. Bold.',
    filter_digital: 'Interfaces. My favourite way to argue with developers.',
    filter_marketing: 'Campaigns and posters. This is where I get loud.',
    filter_identity: 'Identity. Where every pixel is someone’s “let’s try one more option”.',
    empty: 'Nothing here yet. Even I’m surprised.',
    idle_hey_1: 'Hey, you there?',
    idle_hey_2: 'Where did you go?',
    idle_hey_3: 'Hello? I’m showing work here.',
    idle_1: 'Still here. Still no body.',
    idle_2: 'You can pull me. I allow it.',
    idle_3: 'The glasses come off, by the way. Better not, though.',
    idle_4: 'The folders can be dragged. I won’t put them back — no hands.',
    idle_5: 'The case studies won’t look at themselves. Hit “All work”.',
    grab_nose_1: 'That’s my nose. I still need it.',
    grab_nose_2: 'Careful, I sniff out design with that.',
    grab_mouth_1: 'Mmm-mph! I’m talking here!',
    grab_mouth_2: 'Hands off the mouth — I defend mockups with it.',
    grab_cheek_1: 'Cheeks: my tactile interface.',
    grab_cheek_2: 'Ouch. But, I admit, kind of nice.',
    grab_ear_1: 'I can hear you just fine!',
    grab_ear_2: 'The ear is not a volume slider.',
    grab_hair_1: 'This haircut took longer than some logos.',
    grab_hair_2: 'Don’t mess it up, I have a call.',
    grab_chin_1: 'A chin as firm as a deadline.',
    grab_forehead_1: 'Ideas in there. Don’t squeeze them out.',
    grab_eye_1: 'Hey, that’s an eye!',
    grab_glasses_1: 'Careful, that’s optics!',
    stretch_big_1: 'Whoa, I’ve never stretched like that. Not even at stand-up.',
    stretch_big_2: 'Now that’s flexibility. One for the CV.',
    poke_1: 'Ouch!',
    poke_2: 'Poke received.',
    poke_3: 'One more and I’m sending an invoice.',
    glasses_off_1: 'Hey, give the glasses back! Everything’s a blur.',
    glasses_off_2: 'Without glasses all I see is a blurry portfolio.',
    glasses_look: 'Look through the lenses — it’s sharp in there.',
    glasses_self: 'Fine, I’ll put them on myself.',
    glasses_on: 'Thanks. The world is sharp again.',
    tilt_hi: 'Oh, tilting the phone? I see everything.',
    tilt_on: 'Contact. Tilt the phone — I’m watching.',
    tilt_denied: 'Fine, I’ll manage without the tilt.',
    spit_warn: 'Fell asleep over there? I’m about to spit.',
    spit_1: 'Ptooey!',
    spit_2: 'I did warn you.',
    spit_3: 'That’s for doing nothing.',
    spit_4: 'No body, but plenty of spit.',
    spit_5: 'And here.',
    spit_6: 'Hold still, I’m painting.',
    spit_7: 'Just a little more.',
    spit_done: 'Done, the screen is mine. Move — and I’ll wipe it.',
    spit_back: 'Oh, you’re alive! Fine, wiping.',
  },
};

// Какие реплики на какое действие
export const REACTIONS = {
  nose: ['grab_nose_1', 'grab_nose_2'], mouth: ['grab_mouth_1', 'grab_mouth_2'], cheek: ['grab_cheek_1', 'grab_cheek_2'],
  ear: ['grab_ear_1', 'grab_ear_2'], hair: ['grab_hair_1', 'grab_hair_2'], chin: ['grab_chin_1'], forehead: ['grab_forehead_1'],
  eye: ['grab_eye_1'], glasses: ['grab_glasses_1'],
  stretch: ['stretch_big_1', 'stretch_big_2'], poke: ['poke_1', 'poke_2', 'poke_3'],
  glassesOff: ['glasses_off_1', 'glasses_off_2'],
  dragFolder: ['drag_folder_1', 'drag_folder_2', 'drag_folder_far'],
  // посетитель затих: голова окликает его и между делом подсказывает, что тут можно делать
  idle: ['idle_hey_1', 'idle_2', 'idle_hey_2', 'idle_4', 'idle_hey_3', 'idle_3', 'idle_1'],
  // то же, когда папок на главной нет (телефон): вместо подсказки про папки — про кнопку «Все работы»
  idleClean: ['idle_hey_1', 'idle_2', 'idle_hey_2', 'idle_5', 'idle_hey_3', 'idle_3', 'idle_1'],
  // посетитель поставил лайк в каталоге
  like: ['like_1', 'like_2'],
};

// Какие реплики получит посетитель: исходные русские → свои русские → (для другого языка) исходные на нём → свои на нём.
// own — site.lines из содержимого: { ru: { id: 'текст' }, en: { … } }
export function linesFor(lang, own = {}) {
  const mine = (l) => (own && own[l]) || {};
  return { ...LINES.ru, ...mine('ru'), ...(lang !== 'ru' ? { ...(LINES[lang] || {}), ...mine(lang) } : {}) };
}

// Когда какая реплика звучит — для админки («Реплики головы»). В id звёздочка — «своя на каждый раздел сайта»,
// в описании вместо {section} встаёт название раздела.
export const LINE_INFO = [
  { title: 'Приветствие', note: 'Звучит, когда голова собралась на главной.', items: [
    ['hello_1', 'Первый визит: голова здоровается'],
    ['hello_2', 'Сразу следом — на компьютере'],
    ['hello_2_touch', 'Сразу следом — на планшете'],
    ['hello_2_strip', 'Сразу следом — на телефоне, когда папки стоят лентой'],
    ['hello_2_clean', 'Сразу следом — когда папок на главной нет (сейчас так на телефоне)'],
    ['hello_back', 'Посетитель уже был на сайте и вернулся'],
    ['hello_back_clean', 'Вернулся — когда папок на главной нет'],
  ] },
  { title: 'Папки на главной', items: [
    ['folder_*', 'Раскрыли папку «{section}»'],
    ['drag_folder_1', 'Папку перетащили на другое место (звучит одна из двух)'],
    ['drag_folder_2', 'Папку перетащили на другое место (вторая)'],
    ['drag_folder_far', 'Папку унесли к самому краю экрана'],
    ['drag_face', 'Папку положили голове на лицо'],
  ] },
  { title: 'Кнопки', items: [
    ['cv', 'Нажали «CV» — скачивается резюме'],
    ['sound_on', 'Включили звук'],
  ] },
  { title: 'Каталог и кейсы', items: [
    ['catalog_hi', 'Первый раз зашли в каталог — на компьютере'],
    ['catalog_hi_touch', 'Первый раз зашли в каталог — на телефоне или планшете'],
    ['like_1', 'В каталоге поставили лайк'], ['like_2', 'В каталоге поставили лайк (вторая)'],
    ['empty', 'В каталоге пока нет ни одного проекта'],
    ['open_project', 'Открыли кейс'],
  ] },
  { title: 'Посетитель затих', note: 'Оклики на главной: первый — через 7 секунд тишины, следующие — каждые 13 секунд, не больше трёх за одно затишье. Идут по кругу в этом порядке.', items: [
    ['idle_hey_1', 'Оклик 1'], ['idle_2', 'Оклик 2'], ['idle_hey_2', 'Оклик 3'],
    ['idle_4', 'Оклик 4 — когда папки на главной есть'], ['idle_5', 'Оклик 4 — когда папок на главной нет'],
    ['idle_hey_3', 'Оклик 5'], ['idle_3', 'Оклик 6'], ['idle_1', 'Оклик 7'],
  ] },
  { title: 'Голову трогают', note: 'Где реплик несколько, звучит одна из них — по очереди.', items: [
    ['grab_nose_1', 'Схватили за нос'], ['grab_nose_2', 'Схватили за нос (вторая)'],
    ['grab_mouth_1', 'Схватили за рот'], ['grab_mouth_2', 'Схватили за рот (вторая)'],
    ['grab_cheek_1', 'Схватили за щёку'], ['grab_cheek_2', 'Схватили за щёку (вторая)'],
    ['grab_ear_1', 'Схватили за ухо'], ['grab_ear_2', 'Схватили за ухо (вторая)'],
    ['grab_hair_1', 'Схватили за волосы'], ['grab_hair_2', 'Схватили за волосы (вторая)'],
    ['grab_chin_1', 'Схватили за подбородок'],
    ['grab_forehead_1', 'Схватили за лоб'],
    ['grab_eye_1', 'Ткнули в глаз'],
    ['grab_glasses_1', 'Взялись за очки'],
    ['stretch_big_1', 'Сильно растянули и отпустили'], ['stretch_big_2', 'Сильно растянули и отпустили (вторая)'],
    ['poke_1', 'Коротко ткнули'], ['poke_2', 'Коротко ткнули (вторая)'], ['poke_3', 'Коротко ткнули (третья)'],
  ] },
  { title: 'Очки', items: [
    ['glasses_off_1', 'Сняли очки'], ['glasses_off_2', 'Сняли очки (вторая)'],
    ['glasses_look', 'Очки сняты уже три секунды — подсказка, раз за визит'],
    ['glasses_self', 'Очки отпустили далеко от лица — голова надела их сама'],
    ['glasses_on', 'Очки вернули на нос'],
  ] },
  { title: 'Наклон телефона', items: [
    ['tilt_on', 'iPhone: разрешили датчик наклона'],
    ['tilt_denied', 'iPhone: не разрешили'],
    ['tilt_hi', 'Android: телефон первый раз наклонили'],
  ] },
  { title: 'Плевки', note: 'Пасхалка на долгое бездействие; время до неё — в настройках сайта.', items: [
    ['spit_warn', 'Предупреждение перед первым плевком'],
    ['spit_1', 'Первый плевок'],
    ['spit_5', 'После 2-го плевка'],
    ['spit_2', 'После 4-го'],
    ['spit_4', 'После 6-го'],
    ['spit_3', 'После 8-го'],
    ['spit_6', 'После 10-го, если стекло ещё не заполнено'],
    ['spit_7', 'Чистого стекла осталось мало'],
    ['spit_done', 'Стекло заплёвано — серия закончилась'],
    ['spit_back', 'Посетитель пошевелился — стекло вытирается'],
  ] },
];
